version: '3.8'

services:
  ollama-cpu: # This service name is used for internal networking
    image: ollama/ollama:latest
    container_name: ${OLLAMA_CONTAINER_NAME} # Use variable here
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama # Use variable here
    command: serve
    networks:
      - ollama_network

  open-webui: # This service name is used for internal networking
    image: ghcr.io/open-webui/open-webui:latest
    container_name: ${OPENWEBUI_CONTAINER_NAME} # Use variable here
    ports:
      - "${WEBUI_PORT}:8080"
    volumes:
      - open_webui_data:/app/backend/data # Use variable here
    environment:
      # Referencing the service name directly works within the compose network
      - OLLAMA_BASE_URL=http://ollama-cpu:${OLLAMA_PORT}
    depends_on:
      - ollama-cpu
    restart: always
    networks:
      - ollama_network

volumes:
  ollama_data:
    name: ${OLLAMA_VOLUME_NAME}
    external: true
  open_webui_data:
    name: ${OPENWEBUI_VOLUME_NAME}
    external: true

networks:
  ollama_network:
    name: ${NETWORK_NAME}
    driver: bridge
    external: true